### ISSUE TITLE
Unable to download stream with muted bits, despite MP4 conversion disabled.

### ISSUE THREAD

**Issue by Lebon14** [schneidermanuel/TwitchLeecher-Dx#7]
Hi. I've been trying to download this VOD for a good while now to watch locally later: https://www.twitch.tv/videos/1844237156

The log: [TwitchLeecher log 28-08-2023.txt](https://github.com/schneidermanuel/TwitchLeecher-Dx/files/12458130/TwitchLeecher.log.28-08-2023.txt)

Tried twice downloading as MP4. Failed. Tried downloading twice as TS. Failed.
I'm downloading on a NAS with 17TB of free space.

Looking at the log, it tries to download the unmuted vod and when it stumbles upon something that can't be download because it's muted, it fails outright.

> Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/30ae6eb63f5904dff200_droosy_38616551931_1070442622/chunked/2736-unmuted.ts' failed!

Imho, if I had the expertise, if I find muted parts, I would download the video and insert silence in the audio and do that until audio comes back. Maybe have an option to force muted/censored VOD like you would actually watch it on Twitch?

Windows 11 x64 (all patched up)
Ryzen 9 5900X
64GB DDR4 3600 CL16 RAM
EVGA GeForce RTX 3070 Ti
2TB Sabrent Rocket Plus nvme drive

Thanks.

**Comment by schneidermanuel** [comment]
Ok, I did some investigation and it seems, that this is a twitch bug, because this used to work a few months ago. 
I don't know if the problem is the muted parts, but I found out the following

When watching the stream vod on twitch.tv and having a look at the network tab of your browser, the files gets downloaded the same way as twitch-leecher does. Sometimes, this fails with error 403 (forbidden.) This does not only happen in TwitchLeecher-DX, this happens also in the Browser
![image](https://github.com/schneidermanuel/TwitchLeecher-Dx/assets/57318033/44460fde-caa0-403d-bd02-534bab63d574)
![image](https://github.com/schneidermanuel/TwitchLeecher-Dx/assets/57318033/a3653c96-65ed-4f56-8b25-2e203ba75e1f)
Once this error occurs, the vod-playback in the browser fails with error 2000 (A network error occured. try again later)
![image](https://github.com/schneidermanuel/TwitchLeecher-Dx/assets/57318033/38422ccc-3950-4508-8822-0bf7f88a7431)

I will continue to watch this, maybe twitch fixes this anytime soon or I might have to implement something that TwitchLeecher skips this parts.

**Comment by Lebon14** [comment]
> I will continue to watch this, maybe twitch fixes this anytime soon or I might have to implement something that TwitchLeecher skips this parts.

I think this is the best course of action. I'd insert black frames with text, "Unable to get stream information. This might be because the VOD or clip contains muted audio parts and Twitch Leecher-DX was unable to retrieve neither of them. Video will resume when sound resumes."

**Comment by schneidermanuel** [comment]
c2a9ef13396f26610b2e88625f800e4b05c3958c adresses this. 
I will do some cleanup and insert text-frames as @Lebon14 suggested and publish a new version when done. I was able to download the vod's in question with the current build.

**Comment by Lebon14** [comment]
Thank you so much! Will update!
